SOLUTION_NAME ?= hls_operator_colorfilter_sln
SOLUTION_DIR ?= hls_operator_colorfilter_sln

srcs += hls_operator_colorfilter.cpp

WRAPPER ?= hls_operator_colorfilter

include $(SNAP_ROOT)/actions/hls.mk
include ../hls.mk
