SOLUTION_NAME ?= hls_operator_changecase_sln
SOLUTION_DIR ?= hls_operator_changecase_sln

srcs += hls_operator_changecase.cpp

WRAPPER ?= hls_operator_changecase

include $(SNAP_ROOT)/actions/hls.mk
include ../../../../src/metal_fpga/hw/hls/hls.mk
