#! /bin/bash

cat > $_SNAP_ROOT/hardware/sim/testlist.sh <<- EOF
metal_fs /mnt
EOF

chmod +x $_SNAP_ROOT/hardware/sim/testlist.sh
cd $_SNAP_ROOT/hardware/sim/xsim && ../run_sim -explore -list testlist.sh
