#! /bin/bash -e

VIVADO_VERSION=2020.2
VIVADO_EDITION=hl_design_edition  # Choose from hl_design_edition or webpack

docker build \
    -t reg.osmhpi.de/metalfs/xilinx-base:${VIVADO_VERSION} \
    -f ./${VIVADO_VERSION}/Dockerfile \
    .

${VIVADO_VERSION}/installer/Xilinx_unified_*.bin -- -b AuthTokenGen

docker run \
    --name xilinx-vivado-install-${VIVADO_VERSION}-${VIVADO_EDITION} \
    -v $PWD/${VIVADO_VERSION}/installer:/installer \
    -v $PWD/${VIVADO_VERSION}/${VIVADO_EDITION}.txt:/install_config.txt \
    -v $HOME/.Xilinx/wi_authentication_key:/root/.Xilinx/wi_authentication_key \
    reg.osmhpi.de/metalfs/xilinx-base:${VIVADO_VERSION} \
        /bin/bash -c "/installer/Xilinx_Unified_*.bin -- --agree 3rdPartyEULA,WebTalkTerms,XilinxEULA --batch Install --config /install_config.txt"

docker commit \
    --change='ENTRYPOINT []' \
    --change='CMD [ "/bin/bash" ]' \
    xilinx-vivado-install-${VIVADO_VERSION}-${VIVADO_EDITION} \
    reg.osmhpi.de/metalfs/xilinx-vivado:${VIVADO_VERSION}-${VIVADO_EDITION}

docker rm xilinx-vivado-install-${VIVADO_VERSION}-${VIVADO_EDITION}
