SOLUTION_NAME ?= hls_streamgen_sln
SOLUTION_DIR ?= hls_streamgen_sln

HLS_CFLAGS += -std=c++11

srcs += hls_streamgen.cpp

WRAPPER ?= hls_streamgen

include $(SNAP_ROOT)/actions/hls.mk
include ../hls.mk
