#! /bin/bash

cat > $_OCACCEL_ROOT/hardware/sim/testlist.sh <<- EOF
metal_fs /mnt
EOF

chmod +x $_OCACCEL_ROOT/hardware/sim/testlist.sh
mkdir -p $_OCACCEL_ROOT/hardware/sim/xsim
cd $_OCACCEL_ROOT/hardware/sim/xsim && ../run_sim -list testlist.sh
