#! /bin/bash

# Metal FS Development: Try to find metal-driver in cmake build directory
[[ $(type -P "metal-driver") ]] || PATH=$PATH:$METAL_ROOT/build

metal-driver --timeout=30 -vvv --metadata ./metadata -s -f $1
