#include "info.hpp"

void hls_imageinfo() {
    // info_len and info are generated by xxd -i
    #pragma HLS INTERFACE s_axilite port=info_len bundle=ctrl offset=0x010
    #pragma HLS INTERFACE s_axilite port=info bundle=ctrl offset=0x100
    #pragma HLS INTERFACE s_axilite port=return bundle=ctrl
}
