#! /bin/sh -e

image_json=$1
image_basedir=$(dirname $image_json)

jq -r ".operators | to_entries | .[] | [.key, .value] | join(\" \")" $image_json | while read name source; do
    # Check if source starts with "./" using sh syntax
    if case $source in ./*) ;; *) false;; esac; then
        # Operator source is a relative path
        operator_json=$image_basedir/$source/operator.json
    else
        # Operator source is the name of an npm package
        npm_root=$(/bin/sh -c "cd $image_basedir && npm root")
        operator_json=$npm_root/$source/operator.json
    fi

    if [ ! -e $operator_json ]; then
        >&2 echo "Could not find operator.json at $operator_json"
        exit 1
    fi

    printf "${name}\t$(dirname $operator_json)\n"
done
