#! /bin/sh -e

image_json=$1
image_basedir=$(dirname $image_json)

jq -r ".operators | to_entries | .[] | [.key, .value] | join(\" \")" $image_json | while read name source; do

    if /bin/sh -c "cd $image_basedir && test -f $source/operator.json"; then
        # Operator source is a path
        operator_json=$(/bin/sh -c "cd $image_basedir && realpath $source/operator.json")
    else
        # Operator source is the name of an npm package
        npm_root=$(/bin/sh -c "cd $image_basedir && npm root")
        operator_json=$npm_root/$source/operator.json
    fi

    if [ ! -e $operator_json ]; then
        >&2 echo "Could not find operator.json at $operator_json"
        exit 1
    fi

    printf "${name}\t$(dirname $operator_json)\n"
done
