SOLUTION_NAME ?= hls_streamsink_sln
SOLUTION_DIR ?= hls_streamsink_sln

HLS_CFLAGS += -std=c++11

srcs += hls_streamsink.cpp

WRAPPER ?= hls_streamsink

include $(SNAP_ROOT)/actions/hls.mk
include ../hls.mk
