#! /bin/bash -e

PLATFORM=$1

mkdir build && cd build && cmake -DOPTION_BUILD_EXAMPLES=ON .. && make -j4

cd example/src
npm install --production
bash -c "make hw_project"

cd example/src
bash -c "make test_target"

cd example/src
bash -c "make model"
echo "$DRONE_WORKSPACE/build/example-test" > $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/testlist.sh
chmod +x $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/testlist.sh
cd $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/xsim
../run_sim -explore -list testlist.sh -noaet


cd build && ./metal-filesystem-test

cd build && ./metal-pipeline-test
