#!/bin/sh -e

. scripts/env

# push all images
make -C docker/snap push-latest-runtime

DOCKER_TAG=$(echo $DOCKER_TAG | awk '{gsub(/\.[0-9]+$/,"",$1);print}')
while [ ! -z "$DOCKER_TAG" ]; do
    docker tag metalfs/runtime:latest metalfs/runtime:${METAL_TAG}
    docker push metalfs/runtime:${METAL_TAG}
    DOCKER_TAG=$(echo $DOCKER_TAG | awk '{gsub(/\.[0-9]+$/,"",$1);print}')
done
