SOLUTION_NAME ?= hls_operator_blowfish_decrypt_sln
SOLUTION_DIR ?= hls_operator_blowfish_decrypt_sln

srcs += \
	hls_operator_blowfish_decrypt.cpp \
	hls_operator_blowfish_decrypt.h

WRAPPER ?= hls_operator_blowfish_decrypt

include $(SNAP_ROOT)/actions/hls.mk
include ../hls.mk
